### ISSUE TITLE
Reddit comment data

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/The-Pile#2]
priority: medium, shouldnt be too hard since we can use their code

**Comment by leogao2** [comment]
I think we decided not to use the dialogpt script, since they do a bunch of processing we don't need

**Comment by StellaAthena** [comment]
I must have missed that memo, thanks for the correction.

**Comment by thoppe** [comment]
If interested: massive data dumps are at https://pushshift.io/api-parameters/ . The guy who runs it is really into cool research projects, so he'd be able to put together any kind of subset we might want.

**Comment by StellaAthena** [comment]
I believe we talked about using pushshift but it has severe throttling? @leogao2 @Mistobaan what was the deal with that?

**Comment by Mistobaan** [comment]
I haven't been involved in it.

**Comment by StellaAthena** [comment]
@anishthite has uploaded the processing code here: https://github.com/EleutherAI/reddit_comment_processing

Once he provides a link to the URL the data is at this will be moved to “ready to merged.”

**Comment by wassname** [comment]
I guess this was dropped? Would there be any interest in adding reddit comments again? There are 2TB of comments from various sources ([academictorrents](https://academictorrents.com/details/7c0645c94321311bb05bd879ddee4d0eba08aaee), pushshift.io, bigquery). And it's a rich source of natural dialogue data.
