### ISSUE TITLE
Europarl

### ISSUE THREAD

**Issue by StellaAthena** [EleutherAI/The-Pile#25]
Transcripts from EU Parliament meetings from 1996 to 2011. Contains approximately 4.5 GB of text.

Languages: French, Italian, Spanish, Portuguese, Romanian, English, Dutch, German, Danish, Swedish, Bulgarian, Czech, Polish, Slovak, Slovene, Finnish, Hungarian, Estonian, Latvian, Lithuanian, and Greek.

Link: www.statmt.org/europarl/

**Comment by StellaAthena** [comment]
Temporarily closing while we finish version 1.

**Comment by thoppe** [comment]
I could pull this, clean it up and look to see how it's organized if we are still interested. The parallel texts in many languages is interesting too. For v1, do we still want to keep all languages in though?

**Comment by StellaAthena** [comment]
We are pretty much done with V1 (8 GiB short) so I went ahead and removed
the “deferred” label from all of the V2 datasets. You’re welcome to do
this, but it’s going in V2 not V1.

**Comment by thoppe** [comment]
Starting the processing on this. For reference, the data file is 1.5GB but it takes over 14 hours to download from the main site.

**Comment by thoppe** [comment]
This is complete. The processing code is here

https://github.com/thoppe/The-Pile-EuroParl

with the temporary download link here  https://drive.google.com/file/d/15kQ6jAGHsI3ZrA0ibXGuTmzGdib9NA63/view?usp=sharing

      ✔ Saved to EuroParliamentProceedings_1996_2011.jsonl
      ℹ Saved 187,072 articles
      ℹ Uncompressed filesize   4,941,430,389
      ℹ Compressed filesize     1,475,803,930

Once incorporated, this issue can be close and moved to the completed section.
