### ISSUE TITLE
Literotica (replication)

### ISSUE THREAD

**Issue by leogao2** [EleutherAI/The-Pile#32]

**Comment by thoppe** [comment]
From the [prior work](https://www.reddit.com/r/literotica/comments/6xvxvh/i_downloaded_all_380000_stories_on_literotica/): 

> I downloaded all ~380,000 stories on Literotica. Anyone interested in downloading them?
> There are two versions - one with just the raw text of every story in a row and one with the python code used to create it as well as data about every story such as category, tags, # of favorites, etc. with each story in a separate file. The second one is 3.3G compressed and the first one is 9.44G uncompressed and 3.2G compressed.

This dataset was collected about 3 years ago. Currently there are about 480K stories now on the site and a quick sampling shows an uncompressed dataset size of 11.5GB.

**Comment by thoppe** [comment]
Update is complete, and the final size is 12.0GB (this implies that stories over time have gotten longer?). Dataset and source/processing code will be uploaded. @StellaAthena you can close this issue and move it to completed!

**Comment by StellaAthena** [comment]
@thoppe I assume that no PR is required because the code for the pile is the same? It’s just the data that has changed?

**Comment by thoppe** [comment]
No, I rewrote the code for replication purposes. I'm not sure, but I think the original was missing additional pages and only grabbed the first page to each story. This may explain the larger size.
