### ISSUE TITLE
Dataset books3.tar.gz is hosted

### ISSUE THREAD

**Issue by VonChair** [EleutherAI/The-Pile#53]
The books3.tar.gz dataset is now statically hosted at this URL:
https://the-eye.eu/public/AI/pile_preliminary_components/books3.tar.gz
Please add this to the datasets list.

**Comment by leogao2** [comment]
I'll work on adding all the newly-hosted datasets in the next few days.

**Comment by 459737087** [comment]
I can't download it.

**Comment by Luxter77** [comment]
just some context, on [https://the-eye.eu/public/AI/pile/readme.txt](https://the-eye.eu/public/AI/pile/readme.txt) reads:

> The Pile is no longer hosted or distributed by The-Eye or afils.
> It is however still shared among the AI/ML community presumably for its historical significance
> and so can still be found via public torrents.
> 
> Hashes of the original dataset can be obtained from eleuther.ai at request.
> 
> Though The Pile was removed a good while back this file was made due to regular 
> traffic to /public/AI/pile/ from HN reposts of the original paper at eleuther.ai.
> 
> The Pile is old news, check out more recent datasets like; 
> https://huggingface.co/datasets/bigcode/the-stack-v2
>

**Comment by StellaAthena** [comment]
I'm not sure where the "available upon request" part comes from. The hashes can be found [here](https://www.eleuther.ai/hashes) and as we develop and release more datasets we plan on adding them.

**Comment by Synaxis** [comment]
https://the-eye.eu/public/Books/ThoseBooks/
