### ISSUE TITLE
Debate notes

### ISSUE THREAD

**Issue by Hellisotherpeople** [EleutherAI/the-pile#56]
I have this dataset which consists of a large amount of documents compiled by competitive debaters as evidence, along-side extractive and abstractive summaries. Can the documents portion be included in this dataset? I have ~180K documents. 

https://github.com/Hellisotherpeople/DebateSum

**Comment by StellaAthena** [comment]
Hi! Approximately how large is your dataset (in GB, not documents)? And what language(s) is it in?

**Comment by Hellisotherpeople** [comment]
Slightly less than 1GB, English

**Comment by StellaAthena** [comment]
That sounds great! Thanks for bringing it to our attention.

**Comment by QazQazaq** [comment]
This would be a good addition.

**Comment by Hellisotherpeople** [comment]
Is this being included in a future release of the pile? I haven't had a lot of time to spend on this recently but I can try to get it in very soon if there is some kind of time-limit...

**Comment by StellaAthena** [comment]
> Is this being included in a future release of the pile? I haven't had a lot of time to spend on this recently but I can try to get it in very soon if there is some kind of time-limit...

We are not currently working on a Pile V2 or similar. So no.
