### ISSUE TITLE
case.law

### ISSUE THREAD

**Issue by hendrycks** [EleutherAI/the-pile#57]
https://case.law has lots of legal text. There is well over 20 GB of caselaw opinions.
Note this is separate from FreeLaw: "our data [the FreeLaw data], for the moment, is separate" (Mike Lissner, executive director of FreeLaw)
 https://case.law/download/bulk_exports/20200604/by_jurisdiction/case_text_open/ https://case.law/download/bulk_exports/20200604/by_jurisdiction/case_text_restricted/

**Comment by StellaAthena** [comment]
Looks great! Thanks for the suggestion :) You’re welcome to add it if you like, or we can get to it later.

**Comment by hendrycks** [comment]
Oh, and hi Stella. You provided maths advice for UChicago students when I was an incoming student.

**Comment by QazQazaq** [comment]
This would be a good addition.
