### ISSUE TITLE
ImportError: cannot import name 'train_chars' from 'the_pile.pile'

### ISSUE THREAD

**Issue by viashimat** [EleutherAI/The-Pile#67]
Hi,

I'm running Python3.8 on Ubuntu Linux. 

Following the usage instructions, I have been able to run pip install e .

However when I run python the_pile/pile.py --download to download all the data, I get the following error: 

ImportError: cannot import name 'train_chars' from 'the_pile.pile'. 

 Any idea why this is happening and how I can fix it please? 

Thanks in advance.

**Comment by StellaAthena** [comment]
We have been making some changes to the interface over the past couple days. If you try it now, does it work?

**Comment by viashimat** [comment]
Hi Stella,

The problem persists. The error is the same.

**Comment by StellaAthena** [comment]
Is there a specific line or file that is giving that error? I don’t see anything that would try to `import train_chars` from `the-pile\pile.py`

**Comment by viashimat** [comment]
I've re-tested and the code works perfectly now. Thank you so much.

**Comment by StellaAthena** [comment]
Great! Apologies about the problems, but that’s what happens when you use code that hasn’t been released yet :P We expect to have a stable and easy to use version published by the end of the year.
