### ISSUE TITLE
Set up webpage

### ISSUE THREAD

**Issue by leogao2** [EleutherAI/the-pile#69]
We should set up a webpage for the Pile. I'm not entirely settled on any particular design yet; the [SQuAD](https://rajpurkar.github.io/SQuAD-explorer/) page looks nice, but I'm open to other designs. The most important features are:

- A leaderboard. This is very important and probably the only mandatory thring
- Space for a short intro to the pile; I can write this so just put lorem ipsum for now
- A logo for the Pile. We can figure this out slowly

**Comment by aady501** [comment]
Can I start working on this?
