### ISSUE TITLE
Make treemaps

### ISSUE THREAD

**Issue by leogao2** [EleutherAI/the-pile#70]
We should find a way to generate nice treemaps. I think it would be a great way of visualizing how space is allocated in the pile. Features we'd want would include being able to do color coded two-level hierarchy (i.e first we split by category, then by dataset), and it should actually look nice and not like someone drew it in paint.

Something like this but with words and programmatically generated would be perfect:
![image](https://user-images.githubusercontent.com/54557097/98876030-9e736d80-243a-11eb-9c74-1bdbd481bbc9.png)

**Comment by StellaAthena** [comment]
I know how to do this and can do it easily once we have the final sizes.
